FROM eclipse-temurin:23-jdk

LABEL MAINTAINER="chloe"
LABEL name="ssf_13t"

ARG APP_DIR=/APP

WORKDIR ${APP_DIR}

COPY pom.xml .
COPY mvnw .
COPY mvnw.cmd .
COPY src src
COPY .mvn .mvn

RUN chmod a+x ./mvnw && ./mvnw package -Dmaven.test.skip=true

ENV SERVER_PORT=3000

EXPOSE ${SERVER_PORT}

ENTRYPOINT SERVER_PORT=${SERVER_PORT} java -jar target/ssf_13t-0.0.1-SNAPSHOT.jar
# ENTRYPOINT ["java", "-jar", "target/ssf-0.0.1-SNAPSHOT.jar"]